### ISSUE TITLE
HOMEPAGE: (MOBILE) slideshow text is cut off

### ISSUE THREAD

**Issue by drawby** [drawby/shopify-issues#10]
![image](https://cloud.githubusercontent.com/assets/3255301/13056616/6a15847a-d3e4-11e5-860c-f2dee2532508.png)

should look like psd

![image](https://cloud.githubusercontent.com/assets/3255301/13056629/8170f80c-d3e4-11e5-924d-dd2a2b74692f.png)

**Comment by EmilioTelevision** [comment]
this is what it looks like on my phone
![screenshot_2016-02-15-17-22-07](https://cloud.githubusercontent.com/assets/3394886/13061940/04a23dac-d409-11e5-946f-1bc9807513b9.png)

**Comment by drawby** [comment]
i put a mobile media query width 100%.
