### ISSUE TITLE
HOMEPAGE: Slide text is wonky

### ISSUE THREAD

**Issue by drawby** [drawby/shopify-issues#2]
![image](https://cloud.githubusercontent.com/assets/3255301/13014758/7245e5a8-d183-11e5-99d5-43909b6cede9.png)
Gets wierd when you resize screen.

![image](https://cloud.githubusercontent.com/assets/3255301/13014800/ab5a1670-d183-11e5-83eb-cf57c5af5cb8.png)

looks great on big scren tho.

If there is a way to style it a bit better rather than using percents and absolute positioning. I think we used a better method on the ak vault that could work, i will lok into it.

**Comment by EmilioTelevision** [comment]
the hero is laid out fullscreen, positioning is the best solution I just have to work it through all the screensizes

**Comment by EmilioTelevision** [comment]
fixed that 
![image](https://cloud.githubusercontent.com/assets/3394886/13019674/d9d21190-d19e-11e5-8638-2e5882d27454.png)

**Comment by drawby** [comment]
thanks closing out
