### ISSUE TITLE
nav: style + drop down

### ISSUE THREAD

**Issue by GVFTW** [drawby/shopify-issues#39]
lets keep the nav fixed thoughout the site (but keep hidden incentive bar on scroll)

home page w/ drop down hover should look like this

<img width="1098" alt="screen shot 2016-02-19 at 12 14 59 am" src="https://cloud.githubusercontent.com/assets/3649059/13195703/d85a5406-d786-11e5-963e-1695c0b246fb.png">

all other pages

<img width="961" alt="screen shot 2016-02-20 at 4 16 12 am" src="https://cloud.githubusercontent.com/assets/3649059/13195784/b6223eec-d788-11e5-83ed-a586ede98a92.png">

**Comment by EmilioTelevision** [comment]
been having some issues with this one. I cant take the nav out of the container to give the dropdown full width. I been try to place a conditional with javascript but its not playing well the dropdown. Still working on a solution

**Comment by GVFTW** [comment]
not sure if this helps or not, but here is a site that seemingly uses the
same theme and has that functionality
http://shopspring.com/

On Mon, Feb 22, 2016 at 5:10 PM, EmilioTelevision notifications@github.com
wrote:

> been having some issues with this one. I cant take the nav out of the
> container to give the dropdown full width. I been try to place a
> conditional with javascript but its not playing well the dropdown. Still
> working on a sloution
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/drawby/shopify-issues/issues/39#issuecomment-187411230
> .

## 

Gabriel Valverde
516-369-5985

**Comment by EmilioTelevision** [comment]
Sites look similar but they are completely different. They're header is structured to be full width and is not in a grid container like the brooklyn theme. I'm trying to hack it without breaking.

**Comment by GVFTW** [comment]
got it. if we can't figure it out, we can come up with another solution.
hit me up if you want to discuss.

On Mon, Feb 22, 2016 at 9:25 PM, EmilioTelevision notifications@github.com
wrote:

> Sites look similar but they are completely different. They're header is
> structured to be full width and is not in a grid container like the
> brooklyn theme. I'm trying to hack it without breaking.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/drawby/shopify-issues/issues/39#issuecomment-187488825
> .

## 

Gabriel Valverde
516-369-5985

**Comment by EmilioTelevision** [comment]
implemented the original design

**Comment by GVFTW** [comment]
drop down not responsive when adding links

<img width="1364" alt="screen shot 2016-02-24 at 11 35 03 am" src="https://cloud.githubusercontent.com/assets/3649059/13292678/b89adf02-daea-11e5-903d-e1fda431bc53.png">

**Comment by EmilioTelevision** [comment]
this is an issue with the hack. The height is independent of the dropdown. Dropdowns are absolutely positioned so we might have to adjust css when adding to menu

**Comment by GVFTW** [comment]
that's cool, just give me a walk thru after project is complete and i can do it in the future. thanks!

**Comment by EmilioTelevision** [comment]
just edit the height on class .drop-the-top in theme.scss
![image](https://cloud.githubusercontent.com/assets/3394886/13304505/f4b8e636-db22-11e5-9fd0-56d8aef38066.png)
