### ISSUE TITLE
home: blog entry

### ISSUE THREAD

**Issue by GVFTW** [drawby/shopify-issues#41]
- Style text (use About Us as reference)
- Center text
- Hide date
  <img width="1094" alt="screen shot 2016-02-20 at 4 27 09 am" src="https://cloud.githubusercontent.com/assets/3649059/13195850/53e4cfd6-d78a-11e5-9eeb-7847781cedad.png">

**Comment by GVFTW** [comment]
the dot pattern overlay is hosted on another site, we need to host it on ours
<img width="834" alt="screen shot 2016-02-24 at 11 39 51 am" src="https://cloud.githubusercontent.com/assets/3649059/13292854/6cfbbb60-daeb-11e5-8f9d-7e510cb81e6c.png">

**Comment by EmilioTelevision** [comment]
fixed
