### ISSUE TITLE
footer

### ISSUE THREAD

**Issue by GVFTW** [drawby/shopify-issues#42]
- Resize logo
- Style links to turn accent color on hover
- Style Subscribe box button

<img width="1089" alt="screen shot 2016-02-20 at 4 37 13 am" src="https://cloud.githubusercontent.com/assets/3649059/13195886/c180963c-d78b-11e5-9308-db377e7d38f4.png">
- Style for mobile - currently looks like this:

<img width="254" alt="screen shot 2016-02-20 at 4 47 04 am" src="https://cloud.githubusercontent.com/assets/3649059/13195926/0aaad79a-d78d-11e5-9736-b0cfe289003a.png">

should look like this (sorry i never sent this psd)
<img width="250" alt="screen shot 2016-02-20 at 4 46 31 am" src="https://cloud.githubusercontent.com/assets/3649059/13195928/157fa3b2-d78d-11e5-8daa-377c20766431.png">

**Comment by EmilioTelevision** [comment]
![alala-footer-mobile](https://cloud.githubusercontent.com/assets/3394886/13304145/1cc68a54-db21-11e5-9b10-d4417a589ff0.png)
kept the grid structure intact so that the divs are responsive. They float left, hence why they are in the same order as desktop

**Comment by GVFTW** [comment]
i don't love the way it looks with the logo sandwiched between the links, but i can live with it until i find a solution.
we still need to shrink that logo and fix subscribe button
<img width="250" alt="157fa3b2-d78d-11e5-8daa-377c20766431" src="https://cloud.githubusercontent.com/assets/3649059/13304633/ce42e32a-db23-11e5-9967-91cdc966a506.png">

**Comment by EmilioTelevision** [comment]
![alala-footerlogo](https://cloud.githubusercontent.com/assets/3394886/13304929/d1db31c0-db25-11e5-8a90-58a0341b64d1.png)

**Comment by GVFTW** [comment]
awesome logo still a bit big though.
should be keep its size thru responsive scaling
<img width="1089" alt="c180963c-d78b-11e5-9308-db377e7d38f4" src="https://cloud.githubusercontent.com/assets/3649059/13305312/62a9e4b0-db28-11e5-8704-34646946113f.png">
<img width="250" alt="157fa3b2-d78d-11e5-8daa-377c20766431" src="https://cloud.githubusercontent.com/assets/3649059/13305313/62ab1326-db28-11e5-901b-786b990d8003.png">

**Comment by EmilioTelevision** [comment]
it does for me, weird! I resized
![logomobile](https://cloud.githubusercontent.com/assets/3394886/13305507/962c1b7c-db29-11e5-94fa-7c94de706468.png)
![logodesktop](https://cloud.githubusercontent.com/assets/3394886/13305506/962a97d4-db29-11e5-8f1f-e71393f3e31d.png)

**Comment by EmilioTelevision** [comment]
this is what it would look like if it were the same height 
![image](https://cloud.githubusercontent.com/assets/3394886/13305561/12ce98ee-db2a-11e5-86ce-2d6ff40e61b7.png)

**Comment by GVFTW** [comment]
yea your preview looks good!
lets make it this height on desktop and nudge up a few px so its vertically centered
![](https://cloud.githubusercontent.com/assets/3394886/13305561/12ce98ee-db2a-11e5-86ce-2d6ff40e61b7.png)
