### ISSUE TITLE
product: image zoom + breadcrumb

### ISSUE THREAD

**Issue by GVFTW** [drawby/shopify-issues#43]
- Fix Image Zoom Feature
- Style Breadcrumbs (should be same as button text)
- Hide Product Name from breadcrumb
- Remove cents from dollar amount

<img width="332" alt="screen shot 2016-02-20 at 4 57 42 am" src="https://cloud.githubusercontent.com/assets/3649059/13195964/92b6db38-d78e-11e5-8bc0-a9539e0df524.png">
- Slide over size indicator a few pixels life to align with "add to cart" button

<img width="143" alt="screen shot 2016-02-20 at 4 59 55 am" src="https://cloud.githubusercontent.com/assets/3649059/13195980/f71e2bee-d78e-11e5-979e-c75ac82bfa41.png">

**Comment by EmilioTelevision** [comment]
fixed
