### ISSUE TITLE
general: product thumbnails

### ISSUE THREAD

**Issue by GVFTW** [drawby/shopify-issues#44]
- hide sale indicator (red bar on top right corner)

<img width="499" alt="screen shot 2016-02-20 at 1 51 57 am" src="https://cloud.githubusercontent.com/assets/3649059/13196030/c67ece38-d790-11e5-9061-098303c876df.png">
- show 2nd product image on hover. 
  check out how we do it currently at alalastyle.com (2nd image is hovered)

<img width="913" alt="screen shot 2016-02-20 at 5 17 29 am" src="https://cloud.githubusercontent.com/assets/3649059/13196053/4af758d8-d791-11e5-87c9-cd4dfdf36d09.png">

**Comment by GVFTW** [comment]
add color variant to product name

<img width="1087" alt="screen shot 2016-02-20 at 2 51 14 am" src="https://cloud.githubusercontent.com/assets/3649059/13196079/643a5308-d792-11e5-8dd5-4cb0c27b9497.png">

**Comment by GVFTW** [comment]
Product name should be bold

![](https://cloud.githubusercontent.com/assets/3649059/13196079/643a5308-d792-11e5-8dd5-4cb0c27b9497.png)

**Comment by EmilioTelevision** [comment]
![image](https://cloud.githubusercontent.com/assets/3394886/13306925/a19ec958-db35-11e5-81c7-781be1102973.png)
