### ISSUE TITLE
collection: sort questions

### ISSUE THREAD

**Issue by GVFTW** [drawby/shopify-issues#45]
can i edit what goes in sort menu?
would want to hide a couple, and change "price: low to high" to something simpler like "$-$$"
<img width="229" alt="screen shot 2016-02-20 at 5 20 55 am" src="https://cloud.githubusercontent.com/assets/3649059/13196067/c76fe43e-d791-11e5-9175-61c7c748407c.png">

can i edit what goes here?
<img width="231" alt="screen shot 2016-02-20 at 5 21 30 am" src="https://cloud.githubusercontent.com/assets/3649059/13196068/d432d2c6-d791-11e5-964d-cb4083de9665.png">

**Comment by EmilioTelevision** [comment]
hardcoded the menu for desktop to match psd. Mobile is uneditable. http://alala-6.myshopify.com/collections/bottoms

**Comment by EmilioTelevision** [comment]
![bottoms alala](https://cloud.githubusercontent.com/assets/3394886/13200769/0c21eba2-d825-11e5-9af0-014f5ca824c5.png)
![bottoms mobile](https://cloud.githubusercontent.com/assets/3394886/13200772/2b1fe158-d825-11e5-9f9c-e13ddf935276.png)

**Comment by EmilioTelevision** [comment]
so to be clear you can only edit the desktop menus

**Comment by GVFTW** [comment]
Looks great thank you
Can I hide some of the options in the sort menu? Would like to hide:

A-Z
Z-A
Oldest to Newest
Featured

**Comment by EmilioTelevision** [comment]
![sortmobile](https://cloud.githubusercontent.com/assets/3394886/13205166/7538b262-d8af-11e5-9c61-78c9da1b4fa7.png)
![sortmenu](https://cloud.githubusercontent.com/assets/3394886/13205167/753a40f0-d8af-11e5-9e62-f20e46f2a0e7.png)
