### ISSUE TITLE
mobile: text styling

### ISSUE THREAD

**Issue by GVFTW** [drawby/shopify-issues#48]
text column is very narrow
<img width="360" alt="screen shot 2016-02-20 at 5 44 21 am" src="https://cloud.githubusercontent.com/assets/3649059/13196177/2f2d7b38-d795-11e5-969f-0e8551f4545a.png">

**Comment by EmilioTelevision** [comment]
![image](https://cloud.githubusercontent.com/assets/3394886/13199975/b3a21e04-d804-11e5-818b-c96b00a13e44.png)
