### ISSUE TITLE
mobile: product names under thumbnails are white

### ISSUE THREAD

**Issue by GVFTW** [drawby/shopify-issues#49]
<img width="388" alt="screen shot 2016-02-20 at 5 46 52 am" src="https://cloud.githubusercontent.com/assets/3649059/13196191/7fd73790-d795-11e5-8ab8-84288ef365b5.png">

on hover

<img width="380" alt="screen shot 2016-02-20 at 5 46 57 am" src="https://cloud.githubusercontent.com/assets/3649059/13196195/8653dd6c-d795-11e5-87f1-76ee03cab990.png">

**Comment by EmilioTelevision** [comment]
![image](https://cloud.githubusercontent.com/assets/3394886/13199961/1a3784b6-d804-11e5-9f3a-91502ab16fd5.png)
