### ISSUE TITLE
blog: styling for mobile

### ISSUE THREAD

**Issue by GVFTW** [drawby/shopify-issues#51]
currently look like this

on home:
<img width="398" alt="screen shot 2016-02-24 at 5 48 07 pm" src="https://cloud.githubusercontent.com/assets/3649059/13303731/ffd1c3d4-db1e-11e5-91f0-663b4f4f221c.png">

on blog:
<img width="397" alt="screen shot 2016-02-24 at 5 48 33 pm" src="https://cloud.githubusercontent.com/assets/3649059/13303732/ffd34722-db1e-11e5-95ba-68b93d4b0c54.png">

should look like this
on home:
- note image stays this height, and the remaining left and right edges get cropped

<img width="377" alt="screen shot 2016-02-24 at 5 51 09 pm" src="https://cloud.githubusercontent.com/assets/3649059/13303791/4689ac60-db1f-11e5-8afa-8607e138c047.png">

on blog page:
<img width="375" alt="screen shot 2016-02-24 at 5 50 51 pm" src="https://cloud.githubusercontent.com/assets/3649059/13303806/59cc8748-db1f-11e5-8c41-f714ca543cc0.png">

**Comment by EmilioTelevision** [comment]
Im a little confused what you want here? On blog page you want to change date with "news"? 

Also responsive images shouldnt be given pixel height otherwise they will be cropped and unresponsive. We'll hop on chat later to talk through this

**Comment by EmilioTelevision** [comment]
im assuming you're talking about typography. This had to have happened when we were working at the same time because this was addressed a long time ago. Lets communicate when you are editing because I'm spending a lot of time restoring things back too how they were and not on more pressing issues.
![image](https://cloud.githubusercontent.com/assets/3394886/13320119/7bd2ca4e-db94-11e5-8909-6b2863571dac.png)

**Comment by EmilioTelevision** [comment]
![image](https://cloud.githubusercontent.com/assets/3394886/13322085/b4108b38-dba0-11e5-955f-7bc342bfbc74.png)

**Comment by EmilioTelevision** [comment]
did you want to change the timestamp to say featured page one every post? The timestamp is really good for seo purposes 
![image](https://cloud.githubusercontent.com/assets/3394886/13322143/fe1e460c-dba0-11e5-82bf-1b4e86e1b762.png)

**Comment by GVFTW** [comment]
closing this thread as its splitting into 2 seperate issues
