### ISSUE TITLE
collection: mobile thumbnail images

### ISSUE THREAD

**Issue by GVFTW** [drawby/shopify-issues#53]
thumbnails not centered
<img width="397" alt="screen shot 2016-02-24 at 6 07 58 pm" src="https://cloud.githubusercontent.com/assets/3649059/13304526/1cb43078-db23-11e5-88bb-e4f4e320b4e1.png">

**Comment by EmilioTelevision** [comment]
![bras alala](https://cloud.githubusercontent.com/assets/3394886/13305243/ebc93ecc-db27-11e5-9198-8cf216835549.png)
still cant find the sale indicator so I can hide it.

**Comment by GVFTW** [comment]
i was able to hide the sale indicator

<img width="411" alt="screen shot 2016-02-25 at 2 06 58 am" src="https://cloud.githubusercontent.com/assets/3649059/13312455/a9b49f12-db64-11e5-9a90-1853645b9cfc.png">
