### ISSUE TITLE
blog: typography - home post vs. blog feed

### ISSUE THREAD

**Issue by GVFTW** [drawby/shopify-issues#55]
typography should be consistent throughout -
we hid date from homepage because we won't be updating all that much and want content to feel fresh. 

looks like this
home
<img width="1085" alt="screen shot 2016-02-25 at 12 44 02 pm" src="https://cloud.githubusercontent.com/assets/3649059/13328617/914149cc-dbbd-11e5-9453-50cb4d898625.png">

blog
<img width="1088" alt="screen shot 2016-02-25 at 12 44 19 pm" src="https://cloud.githubusercontent.com/assets/3649059/13328626/9858a2aa-dbbd-11e5-9bbc-89f98ba8fec8.png">

both should look like this:
<img width="1106" alt="screen shot 2016-02-25 at 12 46 39 pm" src="https://cloud.githubusercontent.com/assets/3649059/13328662/e1506f06-dbbd-11e5-877b-bd00e2a81990.png">
- on desktop: text should be closer to bottom as seen in mockup
- on desktop: add excerpt text
- on mobile: hide excerpt
- typography: lets use this as the master (right now letter-spacing value is too hight, should be 0.04em, etc.)

<img width="616" alt="screen shot 2016-02-25 at 12 51 12 pm" src="https://cloud.githubusercontent.com/assets/3649059/13328789/9fe0ccc2-dbbe-11e5-99b1-5a3e31ad499c.png">

**Comment by EmilioTelevision** [comment]
made adjustments. on journal text is positioned by %, the last two images have equal height while the first doesn't share dimension and height is much taller
![news alala](https://cloud.githubusercontent.com/assets/3394886/13439049/bb2a22d6-dfb9-11e5-9d67-a746d3ecdeff.png)

**Comment by EmilioTelevision** [comment]
sorry its taking so long, new to shopify and their system but I finally found out what was preventing my positioning. Making mobile edits for it at the moment and going to give the post tags and display that instead of date
![news text](https://cloud.githubusercontent.com/assets/3394886/13450482/cbc235f8-e003-11e5-9c9f-e8b137ce5093.png)

**Comment by GVFTW** [comment]
cool
here is screenshot of what text should look like

<img width="1096" alt="screen shot 2016-03-01 at 11 37 51 pm" src="https://cloud.githubusercontent.com/assets/3649059/13450785/06b4fd3c-e007-11e5-8c80-b7df28e00f72.png">

if its easier to center them vertically like we discussed on the phone earlier - let's go ahead and to that as well
thanks

**Comment by EmilioTelevision** [comment]
it's actually easier at the bottom like psd, ill make the width adjustment now

**Comment by EmilioTelevision** [comment]
![news with tag](https://cloud.githubusercontent.com/assets/3394886/13451761/0d5d514e-e010-11e5-9584-7492cfbdb31c.png)
now has tag instead of date

**Comment by GVFTW** [comment]
since there are still some vertical resizing issues with the text, lets extend the text all the way across

<img width="1095" alt="screen shot 2016-03-02 at 5 55 20 pm" src="https://cloud.githubusercontent.com/assets/3649059/13478733/71598632-e0a0-11e5-9ea2-bdd7b4f32e34.png">

**Comment by EmilioTelevision** [comment]
added

**Comment by GVFTW** [comment]
looks good  - lets remove excerpt text. should read like this screenshot above

**Comment by EmilioTelevision** [comment]
ok removed excerpts
