### ISSUE TITLE
product: remove decimal from price

### ISSUE THREAD

**Issue by GVFTW** [drawby/shopify-issues#57]
looks like 
<img width="426" alt="screen shot 2016-02-25 at 1 01 31 pm" src="https://cloud.githubusercontent.com/assets/3649059/13329052/ef69b64a-dbbf-11e5-9416-c83c66e440bd.png">

should look like 
<img width="332" alt="92b6db38-d78e-11e5-8bc0-a9539e0df524" src="https://cloud.githubusercontent.com/assets/3649059/13329062/f6f9c3c8-dbbf-11e5-90b0-bf74d6632d0e.png">

**Comment by EmilioTelevision** [comment]
done
