### ISSUE TITLE
mobile: various pages

### ISSUE THREAD

**Issue by GVFTW** [drawby/shopify-issues#58]
product page
nudge content up so its flush with the nav
looks like:
<img width="401" alt="screen shot 2016-02-25 at 1 04 39 pm" src="https://cloud.githubusercontent.com/assets/3649059/13329276/f6cec29e-dbc0-11e5-875e-201f6bdeea9a.png">

should be
<img width="402" alt="screen shot 2016-02-25 at 1 04 55 pm" src="https://cloud.githubusercontent.com/assets/3649059/13329314/2e848282-dbc1-11e5-8aec-c386d06d78ff.png">

blog feed
slide this down beneath nav
<img width="399" alt="screen shot 2016-02-25 at 1 05 13 pm" src="https://cloud.githubusercontent.com/assets/3649059/13329286/0265875a-dbc1-11e5-9490-e1f229fe4416.png">

blog post
slide down beneath nav
<img width="400" alt="screen shot 2016-02-25 at 1 11 24 pm" src="https://cloud.githubusercontent.com/assets/3649059/13329347/572083bc-dbc1-11e5-9bbd-769427aacec0.png">

**Comment by EmilioTelevision** [comment]
![sophisticate jacket alala](https://cloud.githubusercontent.com/assets/3394886/13411956/0bb56410-df0e-11e5-94cc-b63df441b3f7.png)
![news alala](https://cloud.githubusercontent.com/assets/3394886/13411957/0bb8918a-df0e-11e5-82c1-cd5eb6f56989.png)
