### ISSUE TITLE
nav: desktop dropdown for pages

### ISSUE THREAD

**Issue by GVFTW** [drawby/shopify-issues#59]
- background these used to be white on alll pages except for home (was like this before i was editing CSS yesterday, so it wasn't me lol)

<img width="1030" alt="screen shot 2016-02-25 at 1 16 47 pm" src="https://cloud.githubusercontent.com/assets/3649059/13329537/6624e834-dbc2-11e5-9de8-6300eff093db.png">

**Comment by EmilioTelevision** [comment]
?? keep the header white on other pages?

**Comment by GVFTW** [comment]
sorry man, meant header + dropdown background, not the text. please change text back to black.
it was right a few days ago, like this -

<img width="961" alt="b6223eec-d788-11e5-83ed-a586ede98a92" src="https://cloud.githubusercontent.com/assets/3649059/13334428/d9b59bc4-dbd9-11e5-9dd4-c1b2f8c1f504.png">

**Comment by EmilioTelevision** [comment]
Text color on hover?

**Comment by GVFTW** [comment]
lets use c7ac7f

can we also use it for text link hover in the footer?

**Comment by EmilioTelevision** [comment]
fixed

**Comment by GVFTW** [comment]
looks great
lets add this styling to page.liquid (i think that's how you do it, but not sure how you pulled it off), so it shows up on additional pages 

<img width="1233" alt="screen shot 2016-02-25 at 11 54 52 pm" src="https://cloud.githubusercontent.com/assets/3649059/13343523/51183ff0-dc1b-11e5-9f41-87c00d92dd22.png">

**Comment by EmilioTelevision** [comment]
![our story alala](https://cloud.githubusercontent.com/assets/3394886/13355651/7471850c-dc6f-11e5-93c3-17c58b7ea99c.png)

**Comment by GVFTW** [comment]
sorry, i was screen shotting you the issue not the solution.

http://alala-6.myshopify.com/pages/our-story and any page created using that template going forward should have the white background.

**Comment by EmilioTelevision** [comment]
if you click the pages in the footer, they are all powered by the page template and have white backgrounds http://alala-6.myshopify.com/pages/returns

**Comment by GVFTW** [comment]
still not working here
http://alala-6.myshopify.com/pages/our-story

or here
http://alala-6.myshopify.com/pages/ss16-lookbook

header should have white background on hover and menu dropdown

**Comment by EmilioTelevision** [comment]
fixed
