### ISSUE TITLE
footer: join button on mobile

### ISSUE THREAD

**Issue by GVFTW** [drawby/shopify-issues#60]
the join button loses its text-transform property on mobile. should be upper case

looks like
<img width="389" alt="screen shot 2016-02-25 at 11 57 20 pm" src="https://cloud.githubusercontent.com/assets/3649059/13343586/fd2bfee4-dc1b-11e5-9403-eea43019f4fd.png">

should look like
<img width="138" alt="screen shot 2016-02-26 at 12 00 55 am" src="https://cloud.githubusercontent.com/assets/3649059/13343595/1d593d94-dc1c-11e5-8310-73fc56c8076d.png">

**Comment by EmilioTelevision** [comment]
![image](https://cloud.githubusercontent.com/assets/3394886/13355749/da60961e-dc6f-11e5-9234-aa2326f9da3b.png)
