### ISSUE TITLE
product: you may also like

### ISSUE THREAD

**Issue by GVFTW** [drawby/shopify-issues#61]
need to bump up product title and meta closer to thumbnail 

DESKTOP
looks like:
<img width="509" alt="screen shot 2016-02-26 at 12 17 27 am" src="https://cloud.githubusercontent.com/assets/3649059/13343816/5d1881ea-dc1e-11e5-91a5-147a94d20584.png">

should look like: (thumbnail from collections page)
<img width="516" alt="screen shot 2016-02-26 at 12 18 07 am" src="https://cloud.githubusercontent.com/assets/3649059/13343835/7ee1679c-dc1e-11e5-8c44-662b1018e7ef.png">

MOBILE
looks like:
<img width="391" alt="screen shot 2016-02-26 at 12 19 31 am" src="https://cloud.githubusercontent.com/assets/3649059/13343865/e1ecac20-dc1e-11e5-9b0b-7e41e4bd55be.png">

should look like
<img width="395" alt="screen shot 2016-02-26 at 12 19 51 am" src="https://cloud.githubusercontent.com/assets/3649059/13343868/ea6bf6e4-dc1e-11e5-83b8-d716b03b9bad.png">

**Comment by EmilioTelevision** [comment]
![image](https://cloud.githubusercontent.com/assets/3394886/13355815/3f6cd176-dc70-11e5-8fb7-585925cefab0.png)
![image](https://cloud.githubusercontent.com/assets/3394886/13355879/812609d4-dc70-11e5-84f1-a14ec4f9d0d0.png)
