### ISSUE TITLE
product: add size guide link

### ISSUE THREAD

**Issue by GVFTW** [drawby/shopify-issues#62]
change text so say "size guide"
 size-guide.png in the assets folder

<img width="410" alt="screen shot 2016-02-26 at 3 11 50 am" src="https://cloud.githubusercontent.com/assets/3649059/13346883/9f343150-dc37-11e5-9ae2-924accadff11.png">

<img width="62" alt="screen shot 2016-02-26 at 3 11 54 am" src="https://cloud.githubusercontent.com/assets/3649059/13346885/a0b9370a-dc37-11e5-915c-fd7e905ce10a.png">

**Comment by EmilioTelevision** [comment]
![image](https://cloud.githubusercontent.com/assets/3394886/13422162/e2dea35a-df60-11e5-8308-53a835b51777.png)
