### ISSUE TITLE
home: hero image text

### ISSUE THREAD

**Issue by GVFTW** [drawby/shopify-issues#63]
text and button is getting cut off now

<img width="1185" alt="screen shot 2016-03-02 at 5 45 54 pm" src="https://cloud.githubusercontent.com/assets/3649059/13478940/9d52d5b2-e0a1-11e5-8cc2-a4fa5e7bc8b0.png">

<img width="530" alt="screen shot 2016-03-02 at 5 46 02 pm" src="https://cloud.githubusercontent.com/assets/3649059/13478930/8e027680-e0a1-11e5-9340-09a0abbc8955.png">

**Comment by EmilioTelevision** [comment]
Do you have the administration bar open? Weird for that to suddenly  change when it hasn't been touched.

**Comment by EmilioTelevision** [comment]
I still dont see this issue on site anywhere
![image](https://cloud.githubusercontent.com/assets/3394886/13481752/44fbfb54-e0b6-11e5-8956-a4099e09a2a3.png)

**Comment by GVFTW** [comment]
yea i think i had the admin bar up
its working ok now
