### ISSUE TITLE
home: featured collections section

### ISSUE THREAD

**Issue by GVFTW** [drawby/shopify-issues#64]
should look like this

desktop
<img width="1098" alt="screen shot 2016-03-02 at 9 38 23 pm" src="https://cloud.githubusercontent.com/assets/3649059/13483047/28f36272-e0bf-11e5-8117-691f4de6c31e.png">

mobile
<img width="372" alt="screen shot 2016-03-02 at 9 39 02 pm" src="https://cloud.githubusercontent.com/assets/3649059/13483060/415a71ca-e0bf-11e5-9617-eacba5637709.png">

**Comment by EmilioTelevision** [comment]
![image](https://cloud.githubusercontent.com/assets/3394886/13484448/d9326424-e0cb-11e5-81b8-6911cd370626.png)
![image](https://cloud.githubusercontent.com/assets/3394886/13484458/f4ca8496-e0cb-11e5-83b6-4be837166280.png)

**Comment by GVFTW** [comment]
cleared my cache, still getting this overlay with the logos. its dim but still there
can we remove overlay entirely? its got a dim on it now thats unneccessary
<img width="320" alt="screen shot 2016-03-03 at 1 39 01 am" src="https://cloud.githubusercontent.com/assets/3649059/13486792/259e06c2-e0e2-11e5-8b6d-d1f2ec1962cf.png">

**Comment by EmilioTelevision** [comment]
fixed 
![image](https://cloud.githubusercontent.com/assets/3394886/13506697/56cf6da6-e14d-11e5-8e87-41a0889f7ed0.png)

**Comment by GVFTW** [comment]
lets remove the dim too

**Comment by EmilioTelevision** [comment]
removed

**Comment by GVFTW** [comment]
can we add more space between image rows on mobile
looks like - 
<img width="393" alt="screen shot 2016-03-04 at 7 52 27 am" src="https://cloud.githubusercontent.com/assets/3649059/13527616/599bdbb4-e1de-11e5-9739-fd6c096726fa.png">

should look like (space between category name and thumbnail images)
<img width="266" alt="screen shot 2016-03-04 at 7 56 16 am" src="https://cloud.githubusercontent.com/assets/3649059/13527646/9c7642f8-e1de-11e5-9c53-03ac01b7d17a.png">

**Comment by EmilioTelevision** [comment]
added 
![image](https://cloud.githubusercontent.com/assets/3394886/13542941/bdb71ee6-e234-11e5-898b-d020e2cc4158.png)

**Comment by GVFTW** [comment]
looks good
