### ISSUE TITLE
home: email capture

### ISSUE THREAD

**Issue by GVFTW** [drawby/shopify-issues#65]
should look like this

<img width="469" alt="screen shot 2016-03-02 at 9 44 08 pm" src="https://cloud.githubusercontent.com/assets/3649059/13483136/efb700c6-e0bf-11e5-9f83-5f79d299e49f.png">

**Comment by EmilioTelevision** [comment]
![image](https://cloud.githubusercontent.com/assets/3394886/13518528/ed820c96-e19c-11e5-91e5-93d1b0146043.png)

**Comment by GVFTW** [comment]
its breaking on my phone
![img_2136](https://cloud.githubusercontent.com/assets/3649059/13527242/be1b1b2a-e1db-11e5-9bb1-2f17bbb3e8d2.PNG)

need to get it closer to original design
<img width="469" alt="screen shot 2016-03-02 at 9 44 08 pm" src="https://cloud.githubusercontent.com/assets/3649059/13527266/e70bfbbc-e1db-11e5-97e7-58fce0da952b.png">

**Comment by EmilioTelevision** [comment]
That skinny width doesn't play nice with that input. This was the lowest
width I could go before the input breaks. The fix would make it wider then
psd.

**Comment by EmilioTelevision** [comment]
![image](https://cloud.githubusercontent.com/assets/3394886/13533611/3784a706-e1ff-11e5-9ece-3b560876cd08.png)

**Comment by GVFTW** [comment]
looks good
can you screenshot me where i can edit the heading and subheading? im going to tweak css a bit

**Comment by EmilioTelevision** [comment]
its an app you will have to purchase. im using the free 14 day trail. app is called wisepops

**Comment by EmilioTelevision** [comment]
http://wisepops.com/

**Comment by EmilioTelevision** [comment]
you can add edits to the theme scss file

**Comment by GVFTW** [comment]
awesome - this is just test shopify account, we are going to purchase full version on the real site! thanks
