### ISSUE TITLE
home page: blog entry

### ISSUE THREAD

**Issue by GVFTW** [drawby/shopify-issues#66]
rearranged via theme > customize theme, and looks like theres some extra padding beneath blog entry
<img width="1172" alt="screen shot 2016-03-03 at 2 10 57 am" src="https://cloud.githubusercontent.com/assets/3649059/13487115/375d17e2-e0e5-11e5-8be7-ca3bd4c3130e.png">

<img width="397" alt="screen shot 2016-03-03 at 2 09 51 am" src="https://cloud.githubusercontent.com/assets/3649059/13487094/1c7a3bda-e0e5-11e5-8a64-df542c70d11c.png">
<img width="1313" alt="screen shot 2016-03-03 at 2 09 37 am" src="https://cloud.githubusercontent.com/assets/3649059/13487095/1d9aa914-e0e5-11e5-9a65-aff5d9649125.png">

**Comment by GVFTW** [comment]
not sure why its not moving with the featured products / spotlight box
<img width="266" alt="screen shot 2016-03-03 at 5 42 57 am" src="https://cloud.githubusercontent.com/assets/3649059/13492026/bd2b6892-e103-11e5-88cb-f55e09a9cee5.png">

**Comment by EmilioTelevision** [comment]
its not moving because thats just a wrapper thats not built into them theme. This is why you build from scratch or design for that theme. featured product wraps around section 4 of the homepage 
![image](https://cloud.githubusercontent.com/assets/3394886/13508086/802a9bde-e153-11e5-8b78-606007c5b058.png)

**Comment by GVFTW** [comment]
ah makes sense. i think that was darby's instructions lol
can we fix it and either
a - style it to theme
b - attach it to the current section # and show me where to edit if I need to move them

thanks

**Comment by EmilioTelevision** [comment]
attached it to the current section. When im done I will create a doc for you

**Comment by GVFTW** [comment]
awesome looks great
