### ISSUE TITLE
blog entry page 

### ISSUE THREAD

**Issue by GVFTW** [drawby/shopify-issues#67]
http://alala-6.myshopify.com/blogs/news/91321347-blog-post-with-image-and-text
1. needs header with white background
2. fix text styles and add padding

looks like this -
<img width="1187" alt="screen shot 2016-03-03 at 2 17 40 am" src="https://cloud.githubusercontent.com/assets/3649059/13487232/37514af6-e0e6-11e5-942b-3c0ca7ced74b.png">

should look like this - 
<img width="1071" alt="screen shot 2016-03-03 at 2 16 20 am" src="https://cloud.githubusercontent.com/assets/3649059/13487239/41fdf454-e0e6-11e5-96ce-e48243b0bd63.png">

**Comment by EmilioTelevision** [comment]
I can't remove the slashes in date, don't have access to that code. 
![image](https://cloud.githubusercontent.com/assets/3394886/13507825/7aa18886-e152-11e5-8c7b-2bf879afa662.png)

**Comment by GVFTW** [comment]
cool, don't sweat it

**Comment by GVFTW** [comment]
tags displaying again in random spots, let's hide them
mobile
<img width="387" alt="screen shot 2016-03-03 at 4 59 03 pm" src="https://cloud.githubusercontent.com/assets/3649059/13511223/5c9667a2-e162-11e5-85b6-c05329328c69.png">
<img width="401" alt="screen shot 2016-03-03 at 4 59 13 pm" src="https://cloud.githubusercontent.com/assets/3649059/13511226/6453180a-e162-11e5-9e33-225e7116f22c.png">

desktop
<img width="1057" alt="screen shot 2016-03-03 at 4 58 37 pm" src="https://cloud.githubusercontent.com/assets/3649059/13511238/6dfa5468-e162-11e5-81ec-4915345cf752.png">
<img width="968" alt="screen shot 2016-03-03 at 4 58 48 pm" src="https://cloud.githubusercontent.com/assets/3649059/13511242/7379cd6a-e162-11e5-84a8-d70b5623f42b.png">
<img width="161" alt="screen shot 2016-03-03 at 4 58 53 pm" src="https://cloud.githubusercontent.com/assets/3649059/13511252/79162458-e162-11e5-8b7a-cb49115b50f5.png">

**Comment by EmilioTelevision** [comment]
hidden
