### ISSUE TITLE
blog type vs. tags 

### ISSUE THREAD

**Issue by GVFTW** [drawby/shopify-issues#68]
homepage blog entry info is feeding from blog type

<img width="715" alt="screen shot 2016-03-02 at 6 20 32 pm" src="https://cloud.githubusercontent.com/assets/3649059/13487299/cebed6ba-e0e6-11e5-914f-431d5a27f3e3.png">
<img width="338" alt="screen shot 2016-03-02 at 6 20 43 pm" src="https://cloud.githubusercontent.com/assets/3649059/13487300/d1afc3f2-e0e6-11e5-8bc3-a79e001f54f5.png">
<img width="792" alt="screen shot 2016-03-03 at 2 23 03 am" src="https://cloud.githubusercontent.com/assets/3649059/13487307/e464713c-e0e6-11e5-99dc-c281e7ae7a61.png">

blog page info feeding from tags

<img width="306" alt="screen shot 2016-03-02 at 6 20 48 pm" src="https://cloud.githubusercontent.com/assets/3649059/13487327/0abc5aca-e0e7-11e5-8006-17d17a43ad63.png">
<img width="615" alt="screen shot 2016-03-03 at 2 24 50 am" src="https://cloud.githubusercontent.com/assets/3649059/13487339/27357ec0-e0e7-11e5-9d17-f8f2703dbfdd.png">

not sure which is easier (think blog type makes more sense), but lets make the source consistent across the board

**Comment by EmilioTelevision** [comment]
displays blog title now

**Comment by GVFTW** [comment]
looks good!
1 - lets get it displayed on home page too
<img width="930" alt="screen shot 2016-03-03 at 3 01 00 pm" src="https://cloud.githubusercontent.com/assets/3649059/13507511/dc2698b4-e150-11e5-8939-266041e2c510.png">

2 - I created a couple of more posts with different blog titles and they're not displaying 
https://alala-6.myshopify.com/admin/articles

<img width="540" alt="screen shot 2016-03-03 at 3 05 11 pm" src="https://cloud.githubusercontent.com/assets/3649059/13507626/5cee381c-e151-11e5-9896-5231be765c62.png">

**Comment by EmilioTelevision** [comment]
they are displaying, in the blog you created e.g, TBT is a new blog, TBT post apear in the tbt blog 
![image](https://cloud.githubusercontent.com/assets/3394886/13508879/df7372d4-e156-11e5-9a55-f9e3a2ed433c.png)
http://alala-6.myshopify.com/blogs/tbt/
having an issue calling the blog title  outside of the blog page so it appears on home. Though I still feel having tags would work better across the board. Will also keep post to one blog not 10 different blogs

**Comment by GVFTW** [comment]
lets do tags then if you think thats best

**Comment by EmilioTelevision** [comment]
tags are in

**Comment by GVFTW** [comment]
dope
