### ISSUE TITLE
home: slide hero image down

### ISSUE THREAD

**Issue by GVFTW** [drawby/shopify-issues#69]
its tucked under the incentive bar and her face gets hidden behind logo on mobile, so lets slide it down a bit while keeping text placement in tact
looks like
<img width="427" alt="screen shot 2016-03-04 at 7 48 21 am" src="https://cloud.githubusercontent.com/assets/3649059/13527522/81fbd9de-e1dd-11e5-9716-dab1db01ee5e.png">

should look like
<img width="429" alt="screen shot 2016-03-04 at 7 48 10 am" src="https://cloud.githubusercontent.com/assets/3649059/13527524/89bb11ee-e1dd-11e5-9b1e-858ffa0960db.png">

**Comment by EmilioTelevision** [comment]
the hero is set to cover the entire screen, If you scroll for one pixel you will it fits perfectly
![image](https://cloud.githubusercontent.com/assets/3394886/13533794/132b640c-e200-11e5-867c-d6f9932b29d9.png)
if i pad the image down there will be a visible gap at the top 
![image](https://cloud.githubusercontent.com/assets/3394886/13533877/7a80933e-e200-11e5-9ecc-732209502a0d.png)
![image](https://cloud.githubusercontent.com/assets/3394886/13533911/96cd7a48-e200-11e5-900a-8272d07f1bc9.png)

**Comment by GVFTW** [comment]
lets slide down anyway, we can't have her face covered on load.
i see what your saying but the girls spend a lot on photography and are gonna complain if you can't see her face

**Comment by EmilioTelevision** [comment]
fixed

**Comment by GVFTW** [comment]
looks good thanks
