### ISSUE TITLE
product: sold out

### ISSUE THREAD

**Issue by GVFTW** [drawby/shopify-issues#70]
looks like
<img width="406" alt="screen shot 2016-03-04 at 8 17 52 am" src="https://cloud.githubusercontent.com/assets/3649059/13528082/dd7bb6fe-e1e1-11e5-86b8-9e8b97da71b2.png">

should be in same spot as add to cart button
<img width="411" alt="screen shot 2016-03-04 at 8 18 01 am" src="https://cloud.githubusercontent.com/assets/3649059/13528089/e9b6ab86-e1e1-11e5-8895-7b4b8a2797d8.png">

**Comment by EmilioTelevision** [comment]
fixed 
![image](https://cloud.githubusercontent.com/assets/3394886/13543248/65ebaabc-e237-11e5-82c5-c2bad7eea016.png)

**Comment by GVFTW** [comment]
good job
