### ISSUE TITLE
PRODUCT PAGE: Size chart for display inline not dropdown

### ISSUE THREAD

**Issue by drawby** [drawby/shopify-issues#9]
![image](https://cloud.githubusercontent.com/assets/3255301/13054665/feafb288-d3d8-11e5-8040-5444c864f913.png)

it should look like the psd like this:

![image](https://cloud.githubusercontent.com/assets/3255301/13054740/60bca256-d3d9-11e5-8a50-470bfe974f2d.png)

**Comment by EmilioTelevision** [comment]
There's js and cms powering this. Not a good idea to change. better to style or leave as is

**Comment by GVFTW** [comment]
<img width="408" alt="screen shot 2016-02-15 at 10 24 01 pm" src="https://cloud.githubusercontent.com/assets/3649059/13066365/10e5d5ea-d433-11e5-90b9-f45b4cfbedd5.png">

theme uses radial buttons for variants as default
they were converted to dropdown when edited to hide color variant (which also displays as default)

you can see default code in product.og.liquid in assets folder, but I am not opposed to styling dropdown if necessary.

**Comment by GVFTW** [comment]
http://alala-6.myshopify.com/products/cross-front-bra-black-leopard
product.og.liquid looks like this 

<img width="394" alt="screen shot 2016-02-15 at 10 37 02 pm" src="https://cloud.githubusercontent.com/assets/3649059/13066509/b48d4614-d434-11e5-9f48-a76b5b19b398.png">

**Comment by EmilioTelevision** [comment]
![image](https://cloud.githubusercontent.com/assets/3394886/13087904/f373da72-d4b7-11e5-877c-4ad7e20327cd.png)

**Comment by drawby** [comment]
looks great im gonna close out issue
